In [18]:
import numpy as np


In [19]:
list1 = [1,2,3,4,5,6,'saroj']
arr1 = np.array(list1)
print(arr1)
type(arr1)

['1' '2' '3' '4' '5' '6' 'saroj']


numpy.ndarray

In [20]:
import numpy as np

list2 = [
  [1, 2, 3, 4],
  [5, 6, 7, 8]
]
arr2 = np.array(list2, dtype='float32')
print(arr2)
print(type(arr2))


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
<class 'numpy.ndarray'>


In [21]:
# create a length 10 nteger array filled with zero
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# create a 3*5 floating point array filled with ones
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# create a 3*5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [24]:
# create an array filled with number in between 0 to 20,with steps

arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [25]:
np.random.normal((3,3))


array([4.05706205, 2.02130401])

In [26]:

arr = np.random.normal(0, 1, (3, 3))
print(arr)


[[ 0.21706833 -0.8223994   0.84631034]
 [ 0.73102769  0.20293514 -0.3872287 ]
 [ 0.49928928 -0.74012326 -0.04789369]]


In [27]:
# create a 3*3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3,3))

array([[3, 6, 5],
       [5, 3, 5],
       [7, 8, 6]])

In [28]:

sample_array = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])

print(f"The dimension of sample array is: {sample_array.ndim}")


The dimension of sample array is: 2


In [29]:

sample_array = np.array([[
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]])

print(f"The dimension of sample array is: {sample_array.ndim}")


The dimension of sample array is: 3


In [30]:

print(f"The shape of sample array is: {sample_array.shape}")



The shape of sample array is: (1, 3, 3)


In [31]:
print(f"The size of sample array is: {sample_array.size}")

The size of sample array is: 9


In [32]:
print(f"The data type of sample array is: {sample_array.dtype}")

The data type of sample array is: int64


In [34]:
# Reshape 1D into another 2D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np.reshape(arr, (4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
# convert 1D array with 8 element to a 2D array with shape (3,3)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.reshape(arr, (3, 3))
  # Answer : No doesnot make 


ValueError: cannot reshape array of size 8 into shape (3,3)

In [38]:
# oncating the array
arr1 = np.array([1,1,1,1])
arr2 = np.array([2,2,2,2])
concat_arr= np.concatenate((arr1,arr2))
concat_arr

array([1, 1, 1, 1, 2, 2, 2, 2])

In [44]:
# For 2dArray concatrnate
a=np.array([
  [1,1,1],
  [1,1,1]
])

b=np.array([
  [2,2,2],
  [2,2,2]
])
concat_arr= np.concatenate((a,b))
concat_arr

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [45]:
# Concatenate 2 D Array (axis=1)
concat_1 = np.concatenate((a, b), axis=1)
print(concat_1)

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


In [47]:
# Splite 1D array i.e[1,2,3,4,5,6] into 4 different parts
arr = np.array([1, 2, 3, 4, 5, 6])

np.split(arr, 4)


ValueError: array split does not result in an equal division

In [50]:
np.array_split(split_array,5)

NameError: name 'split_array' is not defined

In [53]:
import numpy as np

split_array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])

np.array_split(split_array_2d,4,axis=1)


[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]),
 array([], shape=(6, 0), dtype=int64)]

In [42]:
# For 3D Array concatrnate
a=np.array([
  [1,1,1],[1,1,1],
  [1,1,1],[1,1,1]
])

b=np.array([
  [2,2,2],[2,2,2],
  [2,2,2],[2,2,2]
])
concat_arr= np.concatenate((a,b))
concat_arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [58]:
import time
x1 = np.arange(1,100000)
x2 = np.arange(1,100000)

mul = np.zeros(x1.shape)
start_time = time.process_time()

for i in range(len(x1)):
  mul[i] = x1[i]*x2[i]
end_time = time.process_time()

print(end_time - start_time)

0.3526854549999996


In [59]:
# Broadcasting with scalars
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


In [60]:
# broadcasting with 1D and 2D Arrays

a=np.array([1,2,3])
b=np.array([[10],[11],[12]])
print(a+b)

[[11 12 13]
 [12 13 14]
 [13 14 15]]


In [ ]:
# braodcasting with  incompatible space
a=np.array([1,2,3])
b=np.array([[10],[11],[12]])
print(a+b)