In [3]:
import numpy as np


In [38]:
list1 = [1,2,3,4,5,6,'saroj']
arr1 = np.array(list1)
print(arr1)
type(arr1)

['1' '2' '3' '4' '5' '6' 'saroj']


numpy.ndarray

In [12]:
import numpy as np

list2 = [
  [1, 2, 3, 4],
  [5, 6, 7, 8]
]
arr2 = np.array(list2, dtype='float32')
print(arr2)
print(type(arr2))


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
<class 'numpy.ndarray'>


In [13]:
# create a length 10 nteger array filled with zero
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# create a 3*5 floating point array filled with ones
np.ones((3,5), dtype='float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# create a 3*5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [26]:
# create an array filled with number in between 0 to 20,with steps

arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [27]:
np.random.normal((3,3))


[ 0  2  4  6  8 10 12 14 16 18]


In [28]:

arr = np.random.normal(0, 1, (3, 3))
print(arr)


[[ 0.86173258  0.53358369  1.19728763]
 [ 0.52103826 -1.9636064  -0.86371829]
 [ 0.03935406 -1.04431326 -0.15408752]]


In [29]:
# create a 3*3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3,3))

array([[4, 5, 3],
       [9, 5, 9],
       [7, 5, 6]])

In [31]:

sample_array = np.array([
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
])

print(f"The dimension of sample array is: {sample_array.ndim}")


The dimension of sample array is: 2


In [32]:

sample_array = np.array([[
  [1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]
]])

print(f"The dimension of sample array is: {sample_array.ndim}")


The dimension of sample array is: 3


In [33]:

print(f"The shape of sample array is: {sample_array.shape}")



The shape of sample array is: (1, 3, 3)


In [34]:
print(f"The size of sample array is: {sample_array.size}")

The size of sample array is: 9


In [36]:
print(f"The data type of sample array is: {sample_array.dtype}")

The data type of sample array is: int64
