In [3]:
a=np.array([0,1,2,3,4])
print(f'1st item:{a[0]}')
print(f'2nd item:{a[1]}')
print(f'3rd item:{a[2]}')
print(f'4th item:{a[3]}')
print(f'5th item:{a[4]}')

1st item:0
2nd item:1
3rd item:2
4th item:3
5th item:4


In [11]:

arr_idx_2d = np.array([
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19]
])

print(arr_idx_2d[0, 0]) 
print(arr_idx_2d[0, 1]) 
print(arr_idx_2d[0, 3]) 
print(arr_idx_2d[1, 1]) 
print(arr_idx_2d[1, 2]) 


11
12


In [14]:


arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr1_slice = arr1[1:5]
print(arr1_slice)  


[2 3 4 5]


In [15]:
arr1[::2]

array([1, 3, 5, 7])

In [16]:
arr1[-3:-1]

array([5, 6])

In [17]:
arr1[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [22]:
# Slicing 2D array

arr2 = np.array([
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19]
])
arr2[1,1:]


array([18, 19])

In [24]:
base_arr=np.array([1,2,3,4,5,6])
print(base_arr)

[1 2 3 4 5 6]


In [35]:
# to copy array
first_copy_arr = base_arr.copy()
print(first_copy_arr)

[1 2 3 4 5 6]


In [33]:
copy_arr = base_arr #same memory location share or not
print(copy_arr)

[1 2 3 4 5 6]


In [36]:
print(f"""Do original array and copy array shares  an memory?
      Ans:{np.shares_memory(base_arr,first_copy_arr)}""")

Do original array and copy array shares  an memory?
      Ans:False


In [ ]:
def get_